dist: trusty
language: node_js
cache: yarn
notifications:
  email: false
node_js:
- 8
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
before_deploy:
  - yarn run predeploy
deploy:
  provider: pages
  local_dir: out
  skip_cleanup: true
  github_token: $GH_TOKEN