dist: trusty
language: node_js
cache: yarn
notifications:
  email: false
node_js:
- 8
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN